apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
spec:
  serviceName: "couchdb"
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:3.2.1
        env:
          - name: NODE_NETBIOS_NAME
            value: couchdb
          - name: NODENAME
            value: $(NODE_NETBIOS_NAME).couch-service # FQDN in vm.args
          - name: COUCHDB_USER
            value: admin
          - name: COUCHDB_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: DB_PASSWORD
                name: mysecret
          - name: COUCHDB_SECRET
            valueFrom: 
              secretKeyRef: 
                key: DB_PASSWORD
                name: mysecret
        ports:
        - containerPort: 5984
          name: couchdb
        volumeMounts:
        - name: couchdb
          mountPath: /opt/couchdb/data
  volumeClaimTemplates:
  - metadata:
      name: couchdb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi