apiVersion: couchdb.databases.cloud.ibm.com/v1
kind: CouchDBCluster
metadata:
  name: example-couchdbcluster
spec:
  cpu: '1'
  disk: 1Gi
  storageClass: ''
  environment:
    adminPassword: admin
    search: true
  memory: 1Gi
  size: 3
