# permissions for end users to view couchdbcreaters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: couchdbcreater-viewer-role
rules:
- apiGroups:
  - db.couchdb
  resources:
  - couchdbcreaters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.couchdb
  resources:
  - couchdbcreaters/status
  verbs:
  - get
