---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - db.couchdb
  resources:
  - couchdbcreaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.couchdb
  resources:
  - couchdbcreaters/finalizers
  verbs:
  - update
- apiGroups:
  - db.couchdb
  resources:
  - couchdbcreaters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
